language: node_js
node_js:
  - "0.10"
services:
  - mongodb
  - redis-server
after_script:
  - npm run coveralls
env:
  global:
    secure: "IaVYMgXaYkSfPEkuuxQyaSV4jvgFvWy6UiybkFJfFfKY/fk+lxPUv+uIngshYFonEIzcM0EHDI8FfF4A0UVJ0cWFt5wuZcMoO0q6XEpohQL++3+MgyQV9qd56mZi9y3iWOPz51wsed9D8AkndoQfTGsJT/0L/0qxYQJaJrdrtSs="

